version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - REDIS_HOST=redis
      - DEBUG=False
    depends_on:
      - redis
    volumes:
      - ./weather_tiles_cache:/app/weather_tiles_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data: 